### PR TITLE
fix sg ebs

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5)* status: all files reviewed, 2 unresolved discussions (waiting on @radhikabhat08 and @rmyers808)

___
*[README.md, line 101 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5#-MUQKwsO9BT5vmDPgFd_:-MUQKwsO9BT5vmDPgFda:b-l4khl6) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/735bb38345082f8ef4f60b37d6e0a7d6885c5ab2/README.md#L101)):*
> ```Markdown
> ## Block Devices
> 
> ### Root Block Device
> ```

Please use table as done for the similar section in AWS AION readme.
https://github.com/Spirent-Terraform-Modules/terraform-aws-aion#block-devices
___
*[variables.tf, line 79 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5#-MUQLJE2EHasNYPxmvfD:-MUQLJE3A-geUuwsNGiq:b-f71o2e) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/735bb38345082f8ef4f60b37d6e0a7d6885c5ab2/variables.tf#L79)):*
> ```HCL
> 
> variable "root_block_device" {
>   description = " Customize details about the root block device of the instance. See Block Devices below for details."
> ```

nit: remove leading space

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)

___
*[README.md, line 101 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5#-MUQKwsO9BT5vmDPgFd_:-MUQUvht7KMDR08rgNkD:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/735bb38345082f8ef4f60b37d6e0a7d6885c5ab2/README.md#L101)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Please use table as done for the similar section in AWS AION readme.
https://github.com/Spirent-Terraform-Modules/terraform-aws-aion#block-devices
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5#-:-MUQkuId5ZTFT-KqYnW7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @radhikabhat08)

**Review by jhiga — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @radhikabhat08)

**Pull request merged**
