### PR TITLE
feat: initial code

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)

### CODE REVIEW

**Review by used-to-work — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)

___
*[outputs.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRRem4pAsahlyRUV5NC:-MRRem4pAsahlyRUV5ND:bs8tawz) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L8)):*
> ```HCL
> }
> 
> output "id" {
> ```

this is a list so should be `instance_ids` or something plural
___
*[outputs.tf, line 14 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRResKoB_WmFcclbNnz:-MRResKoB_WmFcclbNo-:bb95szd) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L14)):*
> ```HCL
> 
> 
> output "public_ip" {
> ```

Should be plural
___
*[outputs.tf, line 19 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRReulpEPDkZ7K9VLdr:-MRReulpEPDkZ7K9VLds:bb95szd) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L19)):*
> ```HCL
> }
> 
> output "private_ip" {
> ```

Should be plural
___
*[variables.tf, line 7 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRRf6gkE8kg8LEeZmzu:-MRRf6gl5hc11GG4Oin3:b-z54c5f) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/variables.tf#L7)):*
> ```HCL
> }
> 
> variable "instance_name" {
> ```

`instance_name_prefix` might be more accurate?

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: all files reviewed, 8 unresolved discussions (waiting on @radhikabhat08 and @rmyers808)

___
*[cloud-init.yml, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSME012XXBDqdjZDLn:-MRSME012XXBDqdjZDLo:bhul8uu) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/cloud-init.yml#L1)):*
> ```YAML
> #cloud-config
> ```

Please standardize on file name ext (`.yml` or `.yaml`) and contents with @radhikabhat08 .
___
*[main.tf, line 46 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSMoMa3qOuJfCtXwkF:-MRSMoMa3qOuJfCtXwkG:bi90fj0) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/main.tf#L46)):*
> ```HCL
>   }
> 
>   # STCv to GUI/BLL 
> ```

nit: trailing space
___
*[main.tf, line 87 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSMxhU8Lu38n_GADAT:-MRSMxhU8Lu38n_GADAU:b8chtpc) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/main.tf#L87)):*
> ```HCL
> 
> # Create test network interfaces for each instance
> # Each instance will transimt and receive traffic on each test network 
> ```

- transimt -> transmit
- trailing space
___
*[main.tf, line 88 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSN4Y796RYXfpwfTOh:-MRSN4Y796RYXfpwfTOi:bugz5rl) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/main.tf#L88)):*
> ```HCL
> # Create test network interfaces for each instance
> # Each instance will transimt and receive traffic on each test network 
> resource "aws_network_interface" "test" {
> ```

test -> test_traffic (make consistent w/azurerm)

**Review by jhiga — COMMENTED** [review]
@rmyers808 Looks like there are still some comments you didn't address.

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-:-MRYgx6b06-U0Ds_UxNK:b-genh99)* status: all files reviewed, 7 unresolved discussions (waiting on @radhikabhat08 and @rmyers808)

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: 2 of 11 files reviewed, 6 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[main.tf, line 87 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSMxhU8Lu38n_GADAT:-MRZ9TiRAqpsPQRPcL9f:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/main.tf#L87)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

- transimt -> transmit
- trailing space
</blockquote></details>

Done.
___
*[outputs.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRRem4pAsahlyRUV5NC:-MRZ9NMZ8DpUvY3okyS2:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L8)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

this is a list so should be `instance_ids` or something plural
</blockquote></details>

Done.
___
*[outputs.tf, line 14 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRResKoB_WmFcclbNnz:-MRZ9NwQ13M7SE9HnOR7:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L14)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

Should be plural
</blockquote></details>

Done.
___
*[outputs.tf, line 19 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRReulpEPDkZ7K9VLdr:-MRZ9OWpE0g-mxnW7rzW:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/outputs.tf#L19)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

Should be plural
</blockquote></details>

Done.
___
*[variables.tf, line 7 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRRf6gkE8kg8LEeZmzu:-MRZ9_buAIavuVJJmHM_:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/variables.tf#L7)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

`instance_name_prefix` might be more accurate?
</blockquote></details>

Done.
___
*[cloud-init.yml, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRSME012XXBDqdjZDLn:-MRZ9W_S3M49F1YYL67K:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/2e50849e5081afb81722c6bb2ce4d75352a7804f/cloud-init.yml#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Please standardize on file name ext (`.yml` or `.yaml`) and contents with @radhikabhat08 .
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-:-MRa3Be_6ipZK4zN_9ag:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Review by used-to-work — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: all files reviewed, 8 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[variables.tf, line 4 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg6hNC4flJ0sBgMoRW:-MRg6hNC4flJ0sBgMoRX:bvv74jy) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L4)):*
> ```HCL
>   description = "The Spirent TestCenter Virtual AMI. When not specified, the latest marketplace image will be used."
>   type        = string
>   default     = ""
> ```

We should put some validation on here if possible.

eg 

```
validation {
  condition     = var.ami == "" || can(regex("^ami-", var.image_id))
  error_message = "Please provide a valid ami id, starting with \"ami-\". or leave blank"
}
```
___
*[variables.tf, line 10 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg7tmn3-4BTvcgsgtt:-MRg7tmoDHH6bsCPRKB7:b-jckx8l) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L10)):*
> ```HCL
>   description = "AWS VPC ID"
>   type        = string
>   default     = ""
> ```

put some validation and make it start with `vpc-`
___
*[variables.tf, line 33 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg9ICS0YKohUQYd-iY:-MRg9ICS0YKohUQYd-iZ:b-dzckbo) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L33)):*
> ```HCL
> variable "mgmt_plane_subnet" {
>   description = "Management public AWS subnet ID"
>   type        = string
> ```

should start with `subnet-`
___
*[examples/run-stcv-2instances/main.tf, line 18 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg96W0-zjQqW2chbNa:-MRg96W0-zjQqW2chbNb:b-ptki0x) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/examples/run-stcv-2instances/main.tf#L18)):*
> ```HCL
>   mgmt_plane_subnet  = "subnet-ffe75cb2"
>   test_plane_subnets = ["subnet-08766a2cc62ba63bc"]
>   # Warning: Using all adddress cidr block to simplify the example. You should restrict addresses to your public network.
> ```

I'm not clear as to the definition of `public network` here.

**Review by jhiga — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: all files reviewed, 8 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[variables.tf, line 4 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg6hNC4flJ0sBgMoRW:-MRhU6YA42PloI3JqiiZ:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L4)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

We should put some validation on here if possible.

eg 

```
validation {
  condition     = var.ami == "" || can(regex("^ami-", var.image_id))
  error_message = "Please provide a valid ami id, starting with \"ami-\". or leave blank"
}
```

</blockquote></details>

Done.
___
*[variables.tf, line 10 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg7tmn3-4BTvcgsgtt:-MRhU7CA3vN2PwRIDTf4:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L10)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

put some validation and make it start with `vpc-`
</blockquote></details>

Done.
___
*[variables.tf, line 33 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg9ICS0YKohUQYd-iY:-MRhU8R47zmeRo_lWJVA:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/variables.tf#L33)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

should start with `subnet-`
</blockquote></details>

Done.
___
*[examples/run-stcv-2instances/main.tf, line 18 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-MRg96W0-zjQqW2chbNa:-MRhYI5K1wzRtk7K7xe7:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/df25f366e6d086ebbd01be9154866e7f1da6e9e7/examples/run-stcv-2instances/main.tf#L18)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

I'm not clear as to the definition of `public network` here.
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1)* status: all files reviewed, 8 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Review by used-to-work — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/1#-:-MS-jPqg8olO2kmCyfMu:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Pull request merged**
