### PR TITLE
feat: elastic ips

### PR DESCRIPTION
**Pull request by rmyers808**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)

### CODE REVIEW

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[examples/run-stcv-2instances-eip/main.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MS5Pwoe3cn143LLuHn3:-MS5Pwof33SVrDc978JE:b-ujeyhf) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/6eb94957f035f02ae413462ed3e983c0dbf33ad2/examples/run-stcv-2instances-eip/main.tf#L6)):*
> ```HCL
> 
> data "aws_vpc" "default" {
>   id = "vpc-0cf017e5acf05d8e2"
> ```

for security reasons, let's fabricate the IDs used in the example.

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[examples/run-stcv-2instances-eip/main.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MS5Pwoe3cn143LLuHn3:-MS9i6QZ081vu5KF9Tn3:b-iim2ec) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/6eb94957f035f02ae413462ed3e983c0dbf33ad2/examples/run-stcv-2instances-eip/main.tf#L6)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

for security reasons, let's fabricate the IDs used in the example.
</blockquote></details>

Not sure how much we need to worry about ids or other data in examples?  Using tags so config is more portable and can verified w/out much modification.

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[examples/run-stcv-2instances-eip/main.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MS5Pwoe3cn143LLuHn3:-MS9jsTsCZcF6E3xY4ZC:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/6eb94957f035f02ae413462ed3e983c0dbf33ad2/examples/run-stcv-2instances-eip/main.tf#L6)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Not sure how much we need to worry about ids or other data in examples?  Using tags so config is more portable and can verified w/out much modification.
</blockquote></details>

Done.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @radhikabhat08)

___
*[examples/run-stcv-2instances-eip/main.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MS5Pwoe3cn143LLuHn3:-MS9khyCEnmTBNU_JAik:b66102x) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/6eb94957f035f02ae413462ed3e983c0dbf33ad2/examples/run-stcv-2instances-eip/main.tf#L6)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was just looking for something like:
```
data "aws_vpc" "default" {
  id = "your-vpc-id"
}
```

@ltran-spirent  What would you suggest for handling IDs and other customer-specific data in our examples?

**Review by used-to-work — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jhiga, @radhikabhat08, and @rmyers808)

___
*[examples/run-stcv-2instances-eip/main.tf, line 6 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MS5Pwoe3cn143LLuHn3:-MSW8EGt1sK-JFqr4_ML:b-nltnir) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/6eb94957f035f02ae413462ed3e983c0dbf33ad2/examples/run-stcv-2instances-eip/main.tf#L6)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

I was just looking for something like:
```
data "aws_vpc" "default" {
  id = "your-vpc-id"
}
```

@ltran-spirent  What would you suggest for handling IDs and other customer-specific data in our examples?
</blockquote></details>

I would go with something obvious but in the right format.

```data "aws_vpc" "default" {
  id = "vpc-123456789"
}```
```

___
*[examples/run-stcv-2instances-eip/main.tf, line 14 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8Ya80VkRBBlTYPo2:-MSW8Ya80VkRBBlTYPo3:b-k4r3eb) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L14)):*
> ```HCL
>   vpc_id = data.aws_vpc.default.id
>   tags = {
>     ExampleName = "mgmt_plane"
> ```

I'm confused as to why we're adding tags called "ExampleName".  Could I get some elaboration? 
___
*[examples/run-stcv-2instances-eip/main.tf, line 59 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8oS1AhrNnZew6Ai0:-MSW8oS1AhrNnZew6Ai1:bjzokbn) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L59)):*
> ```HCL
>   # Warning: Using all adddress cidr block to simplify the example. You should limit instance access.
>   ingress_cidr_blocks = ["0.0.0.0/0"]
>   key_name            = "spirent_ec2"
> ```

key_name = "bootstrap_key"

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[examples/run-stcv-2instances-eip/main.tf, line 14 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8Ya80VkRBBlTYPo2:-MSZZJh5AQ6MmVQ1uXvD:bcl8ue9) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L14)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

I'm confused as to why we're adding tags called "ExampleName".  Could I get some elaboration? 
</blockquote></details>

For testing purposes I didn't want to rename existing resources so I used the ExampleName tag.  I can change back to just fake IDs appropriate to the resources.  Any ideas to make it easier tor verify module and examples?  Perhaps we should put the fake IDs & key names/files in variables in the examples?  If we do that then we can test the examples w/out having to edit the examples directly and it's clearer what variables are more user/env dependant.
___
*[examples/run-stcv-2instances-eip/main.tf, line 59 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8oS1AhrNnZew6Ai0:-MSZeJhiEWaqQYrQNs_S:bb7m07t) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L59)):*
<details><summary><i>Previously, ltran-spirent (Loc Tran) wrote…</i></summary><blockquote>

key_name = "bootstrap_key"
</blockquote></details>

okay

**Review by rmyers808 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[examples/run-stcv-2instances-eip/main.tf, line 14 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8Ya80VkRBBlTYPo2:-MSaqYiB2Gfkpeh5Quxs:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L14)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

For testing purposes I didn't want to rename existing resources so I used the ExampleName tag.  I can change back to just fake IDs appropriate to the resources.  Any ideas to make it easier tor verify module and examples?  Perhaps we should put the fake IDs & key names/files in variables in the examples?  If we do that then we can test the examples w/out having to edit the examples directly and it's clearer what variables are more user/env dependant.
</blockquote></details>

Done.
___
*[examples/run-stcv-2instances-eip/main.tf, line 59 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-MSW8oS1AhrNnZew6Ai0:-MSaongo1b22yc7JZfrU:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-aws-stcv/blob/b4ec4dddd33c47fe75ec343fa0bb4389e03c6d12/examples/run-stcv-2instances-eip/main.tf#L59)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

okay
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3#-:-MSckPZa-WzS9EevvBJt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Review by radhikabhat08 — APPROVED** [review]
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-aws-stcv/3)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent)

**Pull request merged**
